In [90]:
# %load_ext autoreload
# %autoreload 2
import numpy as np
import azul.tictactoe as logic 
import azul.ai as ai
from random import choice 

state = logic.reset_round()
# state['grid'] = (np.array([
#     [0, 0, 0],
#     [0, 0, 0],
#     [0, 0, 0]
# ]) -1).tolist()
# state['activePlayer'] = 2 -1

while not logic.is_terminal(state):
    # logic.print_state(state)
    action = choice(logic.get_action_space(state))
    print(f"Player {state['activePlayer']}: {action}")
    logic.play(state, action)

logic.print_state(state)
print(logic.get_reward(state))

Player 0: [2, 2]
Player 1: [1, 1]
Player 0: [2, 1]
Player 1: [2, 0]
Player 0: [1, 0]
Player 1: [1, 2]
Player 0: [0, 2]
Player 1: [0, 0]
Player 0: [0, 1]
activePlayer=1	numPlayers=2	startingPlayer=0	roundIdx=0
 1 | 0 | 0
---+---+---
 0 | 1 | 1
---+---+---
 1 | 0 | 0
[0, 0]


In [124]:
state = logic.reset_round()
state['grid'] = (np.array([
    [0, 2, 0, 0],
    [0, 1, 3, 3],
    [1, 2, 2, 3],
    [1, 0, 0, 1]
]) -1).tolist()
state['activePlayer'] = 2 - 1

root = ai.MCTS_node(state)
root.grow(timeout=5)

logic.print_state(state)
# logic.get_reward(state)
# logic.is_terminal(state)
# ai.maxn(state, 8, -100)
root.print()
root.get_best_action()

activePlayer=1	numPlayers=3	startingPlayer=0	roundIdx=0
   | 1 |   |  
---+---+---+---
   | 0 | 2 | 2
---+---+---+---
 0 | 1 | 1 | 2
---+---+---+---
 0 |   |   | 0
self.numRolls=82629, self.numWins=0, self.state['activePlayer']=1
	Action		UCB	WRatio	NumSims
	[0, 0]	0.23	0.172	6725
	[0, 2]	0.23	0.175	7541
	[0, 3]	0.23	0.208	47772
	[1, 0]	0.23	0.174	7336
	[3, 1]	0.23	0.171	6531
	[3, 2]	0.23	0.172	6724


([0, 3], 2)

In [117]:
state = logic.reset_round()
state['grid'] = (np.array([
    [0, 2, 0, 0],
    [0, 1, 3, 3],
    [0, 2, 2, 3],
    [1, 0, 0, 0]
]) -1).tolist()

logic.get_reward(state)

[0.3333333333333333, 0.3333333333333333, 0.3333333333333333]

In [89]:
logic.print_state(state)
# logic.get_reward(state)
# logic.is_terminal(state)
ai.paranoid(state, 7, -np.Inf, np.Inf, state['activePlayer'])

activePlayer=0	numPlayers=3	startingPlayer=0	roundIdx=0
   |   |   |  
---+---+---+---
   |   |   |  
---+---+---+---
   |   |   |  


(0, [0, 0])

In [6]:
logic.print_state(state)

activePlayer=1	numPlayers=2	startingPlayer=0	roundIdx=0
 1 | 0 | 0
---+---+---
 0 | 1 | 1
---+---+---
 1 | 0 | 0


In [137]:
row, col = [int(s) for s in inp.split(" ")]

row, col

(1, 2)

In [9]:
# Simulate a full game
import azul.ai as ai
from random import seed 
import azul.logic as logic
from copy import deepcopy
# seed(1)

t = logic.Table()
state = t.get_observation()

agents = [
    lambda state: ai.get_random_action(state),
    # lambda state: ai.alphabeta(state, 1, 4, -np.Inf, np.Inf, state['activePlayer'])[1],
    # lambda state: ai.negamax(state, 1, 4, state['activePlayer'])[1],
    lambda state: ai.get_random_action(state),
]

info = []
while not (t.is_round_over() and t.is_game_over()):
    state = deepcopy(t.get_observation())
    action = agents[state['activePlayer']](state)
    
    factoryIdx, color, row = action
    assert t.is_valid(color, factoryIdx, row), "Invalid action"
    info.append({'state': deepcopy(state), 'action': action})
    t.step_move(color, factoryIdx, row)

# ai.get_reward(state), state
ai.get_reward(t.get_observation()), t.get_observation()

([2, 0],
 {'factory': [[], [], [], [], []],
  'center': [],
  'player': [{'grid': [[1, 2, 3, 4, 5],
     [5, 0, 0, 3, 0],
     [0, 0, 1, 0, 3],
     [0, 4, 0, 0, 0],
     [0, 3, 0, 0, 0]],
    'line': [[], [2], [], [1, 1], [1, 1, 1]],
    'score': 0,
    'floor': []},
   {'grid': [[1, 2, 0, 4, 5],
     [0, 1, 0, 3, 4],
     [0, 0, 0, 2, 0],
     [0, 4, 0, 0, 0],
     [0, 0, 0, 5, 0]],
    'line': [[], [], [1], [3, 3, 3], []],
    'score': 0,
    'floor': []}],
  'activePlayer': 0,
  'roundIdx': 6})

In [8]:
info[0]

{'state': {'factory': [[3, 4, 1, 2],
   [2, 2, 2, 4],
   [2, 4, 1, 5],
   [4, 1, 1, 3],
   [4, 1, 5, 4]],
  'center': [-1],
  'player': [{'grid': [[0, 0, 0, 0, 0],
     [0, 0, 0, 0, 0],
     [0, 0, 0, 0, 0],
     [0, 0, 0, 0, 0],
     [0, 0, 0, 0, 0]],
    'line': [[], [], [], [], []],
    'score': 0,
    'floor': []},
   {'grid': [[0, 0, 0, 0, 0],
     [0, 0, 0, 0, 0],
     [0, 0, 0, 0, 0],
     [0, 0, 0, 0, 0],
     [0, 0, 0, 0, 0]],
    'line': [[], [], [], [], []],
    'score': 0,
    'floor': []}],
  'activePlayer': 0,
  'roundIdx': 0},
 'action': [4, 4, 2]}

In [10]:
# from azul.ai import get_reward_simple, get_reward, negamax, alphabeta
import azul.ai as ai
from copy import deepcopy

# t = logic.Table()
# obs = t.get_observation()
obs = logic.reset_round()

# ai.negamax(obs, 1, 4, obs['activePlayer']), \
# ai.alphabeta(obs, 1, 4, -np.Inf, np.Inf, obs['activePlayer'])
# ai.alphabeta(obs, 1, 4, -np.Inf, np.Inf, obs['activePlayer'])

# ai.get_reward_simple(obs)
rewards = []
actions = logic.get_action_space(obs)
for action in actions:
    state = deepcopy(obs)
    logic.play(state, action)
    rewards.append(logic.get_reward_simple(state))

# ai.negamax(deepcopy(obs), 1, 2, obs['activePlayer']), \
ai.alphabeta(deepcopy(obs), 1, 2, -np.Inf, np.Inf, obs['activePlayer']), \
    actions, rewards

# ai.is_terminal(obs)

AttributeError: 'numpy.ndarray' object has no attribute 'index'

In [96]:
# Simulate a full game
state = ai.reset_round()

agents = [
    # lambda state: ai.get_random_action(state),
    lambda state: ai.alphabeta(state, 1, 3, -np.Inf, np.Inf, state['activePlayer'])[1],
    lambda state: ai.get_random_action(state),
]

while not ai.is_game_over(state):
    while not ai.is_terminal(state):
        action = agents[state['activePlayer']](state)
        assert ai.is_valid_action(state, action), "Invalid action"
        ai.play(state, action)

    ai.reset_round(state)

ai.get_reward(state), state

([0, 8],
 {'factory': [[], [], [], [], []],
  'center': [],
  'player': [{'grid': [[0, 0, 3, 0, 0],
     [0, 0, 0, 0, 4],
     [0, 0, 0, 0, 0],
     [0, 0, 0, 0, 0],
     [0, 0, 0, 0, 0]],
    'line': [[], [], [], [], []],
    'score': 0,
    'floor': []},
   {'grid': [[1, 2, 3, 4, 5],
     [5, 0, 2, 0, 4],
     [0, 0, 0, 0, 0],
     [3, 4, 5, 0, 0],
     [0, 0, 0, 0, 0]],
    'line': [[], [], [1, 1], [], [2, 2]],
    'score': 8,
    'floor': []}],
  'activePlayer': 1,
  'roundIdx': 5})

In [72]:
state['player'][1]

{'grid': [[1, 2, 3, 4, 5],
  [5, 0, 0, 0, 0],
  [0, 5, 0, 2, 0],
  [0, 0, 0, 0, 2],
  [0, 0, 0, 0, 0]],
 'line': [[], [3], [4, 4], [], [4, 4, 4]],
 'score': 2,
 'floor': [3,
  2,
  5,
  5,
  1,
  3,
  2,
  2,
  2,
  3,
  1,
  1,
  1,
  1,
  1,
  5,
  5,
  5,
  5,
  1,
  1,
  1,
  1,
  3,
  3,
  2,
  2,
  2,
  3,
  2,
  2,
  2,
  3,
  5,
  5]}

In [67]:
np.array([[]] * 5).tolist()

[[], [], [], [], []]

In [38]:
t = logic.Table()
obs = t.get_observation()

ai.negamax(deepcopy(obs), 1, 2, obs['activePlayer'])  # 4.6s
# ai.alphabeta(deepcopy(obs), 1, 3, -np.Inf, np.Inf, obs['activePlayer'])

(1, [4, 1, 2])

In [40]:
from azul.ai import get_heuristics
from copy import deepcopy

t = azul.Table()
rewards = []
for reps in range(1):
    obs = t.get_observation()

    obs['player'][0]['line'][4] = [1]

    obs['player'][0]['grid'] = [
        [0, 0, 0, 0, 0],
        [0, 0, 2, 0, 0],
        [0, 0, 1, 0, 0],
        [0, 0, 5, 0, 0],
        [0, 0, 4, 0, 0]]

    obs['player'][1]['grid'] = [
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]]

    obs['player'][2]['grid'] = [
        [0, 0, 3, 0, 0],
        [0, 0, 2, 0, 0],
        [0, 5, 0, 0, 0],
        [0, 0, 5, 0, 0],
        [0, 0, 0, 0, 0]]
    
    rewards.append(get_heuristics(obs))

# get_heuristics(obs), obs['player']
# min([min([g.count(0) for g in p['grid']]) for p in obs['player']])
obs['player']
# np.mean(rewards, axis=0), np.std(rewards, axis=0)


ImportError: cannot import name 'get_heuristics' from 'azul.ai' (/home/garamizo/Azul-Board-Game/azul/ai.py)

In [ ]:
# %%timeit 
from azul.ai import get_random_action, get_action_space, play, is_terminal, get_reward, MCTS_node, get_winner
from azul.logic import random_move 

t = azul.Table()
obs = t.get_observation()
obsOld = deepcopy(obs)

root = MCTS_node(obsOld)
MCTS_node.grow(root, timeout=1.0)

# action = get_random_action(obs)  # 35 us
action, _ = MCTS_node.get_best_action(root)

play(obs, action)

# random_move(obs)  # 19.9 us
# get_action_space(obs)
# play(obs, action)
# action, obs
# get_reward(obs)
# len(root.action)
# root.rollout()

# root.print()
rootNew = MCTS_node.search_node(root, obs)
# obs, obsOld
rootNew.print()
root.print()

self.numRolls=26, self.numWins=18, self.state['activePlayer']=1
	Action		UCB	WRatio	NumSims
	[-1, 3, -1]	2.55	0.000	1
	[-1, 3, 0]	3.55	1.000	1
	[-1, 3, 4]	3.55	1.000	1
	[-1, 4, 3]	2.55	0.000	1
	[0, 4, 1]	2.55	0.000	1
	[0, 4, 2]	2.55	0.000	1
	[0, 4, 4]	3.55	1.000	1
	[0, 5, 2]	2.55	0.000	1
	[0, 5, 4]	2.55	0.000	1
	[1, 1, 0]	2.55	0.000	1
	[1, 1, 3]	2.55	0.000	1
	[1, 2, -1]	2.55	0.000	1
	[1, 2, 0]	2.55	0.000	1
	[1, 2, 1]	2.55	0.000	1
	[1, 5, -1]	3.55	1.000	1
	[2, 3, 4]	3.55	1.000	1
	[2, 4, 1]	2.55	0.000	1
	[2, 4, 2]	2.55	0.000	1
	[2, 4, 4]	2.55	0.000	1
	[3, 2, 2]	3.55	1.000	1
	[3, 4, 3]	2.55	0.000	1
	[3, 4, 4]	2.55	0.000	1
	[3, 5, 0]	3.55	1.000	1
	[3, 5, 1]	2.55	0.000	1
	[3, 5, 2]	3.55	1.000	1
self.numRolls=1468, self.numWins=0, self.state['activePlayer']=0
	Action		UCB	WRatio	NumSims
	[0, 3, -1]	1.41	0.200	10
	[0, 3, 0]	1.44	0.680	25
	[0, 3, 1]	1.39	0.438	16
	[0, 3, 2]	1.40	0.526	19
	[0, 3, 3]	1.40	0.471	17
	[0, 3, 4]	1.40	0.640	25
	[0, 4, -1]	1.44	0.333	12
	[0, 4, 0]	1.40	0.550	20
	[0, 4

In [ ]:
# == takes 80.2 ns
actions = {'a':[1, 1, 2], 'b':[2, 1, 1], 'c':[3, 2, 1]}
actions2 = {'a':[1, 1, 2], 'b':[2, 1, 1]}
actions2['c'] = [3, 2, 1]

# == takes 64 ns
# actions = [[1, 1, 2], [2, 1, 1], [3, 2, 1]]
# actions2 = [[1, 1, 2], [2, 1, 1]]
# actions2.append([3, 2, 1])
# b = [1, 2]

child = {str(a): None for a in actions}

actions == actions2
# actions, actions2
# b == None
str(actions)

"{'a': [1, 1, 2], 'b': [2, 1, 1], 'c': [3, 2, 1]}"

In [ ]:
%load_ext autoreload
%autoreload 2

from azul.ai import MCTS_node, get_random_action
from azul.logic import random_move, Table

t = Table()
obs = t.get_observation()

root = MCTS_node(obs, 0)
root.grow()

root.print()

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload
self.numRolls=2638, self.numWins=0, self.state['activePlayer']=0
	Action		UCB	WRatio	NumSims
	[0, 1, -1]	1.24	0.462	26
	[0, 1, 0]	1.23	0.417	24
	[0, 1, 1]	1.22	0.500	30
	[0, 1, 2]	1.23	0.440	25
	[0, 1, 3]	1.23	0.440	25
	[0, 1, 4]	1.23	0.440	25
	[0, 2, -1]	1.25	0.500	28
	[0, 2, 0]	1.25	0.481	27
	[0, 2, 1]	1.24	0.350	20
	[0, 2, 2]	1.24	0.545	33
	[0, 2, 3]	1.24	0.462	26
	[0, 2, 4]	1.24	0.462	26
	[0, 3, -1]	1.24	0.559	34
	[0, 3, 0]	1.25	0.481	27
	[0, 3, 1]	1.24	0.571	35
	[0, 3, 2]	1.24	0.462	26
	[0, 3, 3]	1.23	0.440	25
	[0, 3, 4]	1.25	0.500	28
	[0, 5, -1]	1.25	0.595	37
	[0, 5, 0]	1.23	0.440	25
	[0, 5, 1]	1.23	0.440	25
	[0, 5, 2]	1.22	0.391	23
	[0, 5, 3]	1.22	0.391	23
	[0, 5, 4]	1.25	0.500	28
	[1, 3, -1]	1.24	0.583	36
	[1, 3, 0]	1.23	0.516	31
	[1, 3, 1]	1.25	0.481	27
	[1, 3, 2]	1.23	0.531	32
	[1, 3, 3]	1.23	0.440	25
	[1, 3, 4]	1.24	0.571	35
	[1, 4, -1]	1.25	0.381	21
	[1, 4, 0]	1.25	0.381	21
	[1, 4, 1]	1.

In [ ]:
a = 1 
b = None

if a is not None:
    print('not none')

if a is None or b is None:
    print('none')

not none
none


In [ ]:
grid = np.array([
    [0, 2, 3, 4, 5],
    [5, 1, 2, 3, 4],
    [4, 5, 1, 2, 3],
    [3, 4, 5, 1, 2],
    [2, 3, 4, 5, 1]])
np.sum(grid == 1)

discard = [1, 2, 2, 1, 2, 4]
# if discard.count(-1) > 0:
#     discard.remove(-1)
# np.random.permutation(discard)
# discard.remove(1)
discard.clear()
discard

[]

In [ ]:
np.random.seed(100)
t = azul.Table()

# t.player[0].grid = np.array([
#     [1, 2, 3, 4, 5],
#     [0, 1, 0, 3, 4],
#     [4, 0, 1, 0, 3],
#     [0, 4, 0, 0, 2],
#     [0, 3, 4, 0, 0]])

# t.step_move(mark=5, factoryIdx=0, playerIdx=0, row=1)
# t.step_move(mark=5, factoryIdx=6, playerIdx=0, row=2)
# t.step_move(mark=1, factoryIdx=-1, playerIdx=0, row=4)
# t.print()
# t.player[0].print()
obs = t.get_observation()

# mark, factoryIdx, row = azul.random_move(0, obs)
# mark, factoryIdx, row
playerPolicyFcn = [azul.random_move] * 3
t.step_round(playerPolicyFcn)
# mark, factoryIdx, row = playerPolicyFcn[0](
#     0, obs)
# len(obs['factory'])
t.print()

[]
[]
[]
[]
[]
  []
[[], [3], [2], [], [4, 4, 4]]
[[1. 2. 3. 4. 5.]
 [5. 0. 2. 0. 4.]
 [4. 5. 0. 0. 0.]
 [3. 4. 0. 1. 0.]
 [2. 0. 0. 0. 0.]]
[]
8
---
[[], [3], [4], [2, 2], []]
[[1. 2. 3. 4. 5.]
 [5. 1. 2. 0. 4.]
 [0. 5. 1. 2. 3.]
 [3. 0. 0. 0. 0.]
 [0. 3. 0. 5. 0.]]
[]
31
---




In [ ]:
t.print()
t.player[0].print()
t.player[1].print()

obs = t.get_observation()
azul.valid_move(obs,playerIdx=0, factoryIdx=-1, mark=5, row=1)

[]
[]
[]
[]
[]
  [1, 1, 1]
---
[[3], [3], [5], [4, 4, 4], [5, 5]]
[[0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 0. 2. 0.]
 [0. 0. 0. 0. 0.]
 [0. 3. 0. 0. 0.]]
[-1, 3, 3, 3]
4
---
[[5], [5], [2, 2, 2], [5, 5, 5], [4, 4, 4, 4, 4]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[5, 5]
0
---


False