In [2]:
# %load_ext autoreload
# %autoreload 2

import numpy as np
import azul.logic as azul

bag = np.tile(np.arange(1, 6), 2)

p = azul.Board()
p.grid = np.array([
    [1, 2, 3, 0, 5],
    [0, 1, 0, 3, 4],
    [4, 0, 1, 0, 3],
    [0, 4, 0, 0, 2],
    [0, 3, 4, 0, 0]])
p.line[0] = [4]
p.line[2] = [5, 5, 5]
p.line[3] = [3, 3]

p.step_move(mark=1, numMark=3, row=4, isFirst=True)
# p.step_move(1, 5, 4, False)
# p.step_move(2, 2, -1, False)

# p.print()
# discard = p.step_round()
# p.print()
# print("Final Score: ", p.score_board())
# discard

In [11]:
a = 1 
b = None

if a is not None:
    print('not none')

if a is None or b is None:
    print('none')

not none
none


In [37]:
grid = np.array([
    [0, 2, 3, 4, 5],
    [5, 1, 2, 3, 4],
    [4, 5, 1, 2, 3],
    [3, 4, 5, 1, 2],
    [2, 3, 4, 5, 1]])
np.sum(grid == 1)

discard = [1, 2, 2, 1, 2, 4]
# if discard.count(-1) > 0:
#     discard.remove(-1)
# np.random.permutation(discard)
# discard.remove(1)
discard.clear()
discard

[]

In [157]:
np.random.seed(100)
t = azul.Table()

# t.player[0].grid = np.array([
#     [1, 2, 3, 4, 5],
#     [0, 1, 0, 3, 4],
#     [4, 0, 1, 0, 3],
#     [0, 4, 0, 0, 2],
#     [0, 3, 4, 0, 0]])

# t.step_move(mark=5, factoryIdx=0, playerIdx=0, row=1)
# t.step_move(mark=5, factoryIdx=6, playerIdx=0, row=2)
# t.step_move(mark=1, factoryIdx=-1, playerIdx=0, row=4)
# t.print()
# t.player[0].print()
obs = t.get_observation()

# mark, factoryIdx, row = azul.random_move(0, obs)
# mark, factoryIdx, row
playerPolicyFcn = [azul.random_move] * 3
t.step_round(playerPolicyFcn)
# mark, factoryIdx, row = playerPolicyFcn[0](
#     0, obs)
# len(obs['factory'])
t.print()

[]
[]
[]
[]
[]
  []
[[], [3], [2], [], [4, 4, 4]]
[[1. 2. 3. 4. 5.]
 [5. 0. 2. 0. 4.]
 [4. 5. 0. 0. 0.]
 [3. 4. 0. 1. 0.]
 [2. 0. 0. 0. 0.]]
[]
8
---
[[], [3], [4], [2, 2], []]
[[1. 2. 3. 4. 5.]
 [5. 1. 2. 0. 4.]
 [0. 5. 1. 2. 3.]
 [3. 0. 0. 0. 0.]
 [0. 3. 0. 5. 0.]]
[]
31
---




In [147]:
t.print()
t.player[0].print()
t.player[1].print()

obs = t.get_observation()
azul.valid_move(obs,playerIdx=0, factoryIdx=-1, mark=5, row=1)

[]
[]
[]
[]
[]
  [1, 1, 1]
---
[[3], [3], [5], [4, 4, 4], [5, 5]]
[[0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 0. 2. 0.]
 [0. 0. 0. 0. 0.]
 [0. 3. 0. 0. 0.]]
[-1, 3, 3, 3]
4
---
[[5], [5], [2, 2, 2], [5, 5, 5], [4, 4, 4, 4, 4]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[5, 5]
0
---


False