In [15]:
%load_ext autoreload
%autoreload 2

import numpy as np
import azul.logic as azul

bag = np.tile(np.arange(1, 6), 2)

p = azul.Board()
p.grid = np.array([
    [1, 2, 3, 0, 5],
    [0, 1, 0, 3, 4],
    [4, 0, 1, 0, 3],
    [0, 4, 0, 0, 2],
    [0, 3, 4, 0, 0]])
p.line[0] = [4]
p.line[2] = [5, 5, 5]
p.line[3] = [3, 3]

p.step_move(mark=1, numMark=3, row=4, isFirst=True)
# p.step_move(1, 5, 4, False)
# p.step_move(2, 2, -1, False)

# p.print()
# discard = p.step_round()
# p.print()
# print("Final Score: ", p.score_board())
# discard

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [142]:
# gridRow = [[1, 2, 3, 0, 5], [10, 20, 30, 40, 50]]
val = [2] * 5 + [1]
# [g for g in gridRow if g > 0]
# gridRow.remove(1)
# gridRow.index(2)
# 10 in gridRow[0]
None in val

False

In [134]:
from azul.ai import get_heuristics
from copy import deepcopy

t = azul.Table()
rewards = []
for reps in range(1):
    obs = t.get_observation()

    obs['player'][0]['line'][4] = [1]

    obs['player'][0]['grid'] = [
        [0, 0, 0, 0, 0],
        [0, 0, 2, 0, 0],
        [0, 0, 1, 0, 0],
        [0, 0, 5, 0, 0],
        [0, 0, 4, 0, 0]]

    obs['player'][1]['grid'] = [
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]]

    obs['player'][2]['grid'] = [
        [0, 0, 3, 0, 0],
        [0, 0, 2, 0, 0],
        [0, 5, 0, 0, 0],
        [0, 0, 5, 0, 0],
        [0, 0, 0, 0, 0]]
    
    rewards.append(get_heuristics(obs))

# get_heuristics(obs), obs['player']
# min([min([g.count(0) for g in p['grid']]) for p in obs['player']])
obs['player']
# np.mean(rewards, axis=0), np.std(rewards, axis=0)


[{'grid': [[1, 2, 3, 0, 0],
   [5, 1, 2, 3, 4],
   [0, 5, 1, 0, 3],
   [3, 4, 5, 0, 2],
   [0, 0, 4, 0, 1]],
  'line': [[], [], [], [], []],
  'score': 54,
  'floor': []},
 {'grid': [[0, 2, 3, 4, 5],
   [5, 1, 2, 3, 0],
   [0, 0, 1, 0, 3],
   [3, 4, 0, 1, 2],
   [0, 3, 0, 0, 1]],
  'line': [[], [], [], [], []],
  'score': 50,
  'floor': []},
 {'grid': [[1, 2, 3, 4, 5],
   [5, 0, 2, 3, 4],
   [4, 5, 0, 2, 3],
   [3, 0, 5, 0, 2],
   [2, 0, 0, 5, 0]],
  'line': [[], [], [], [], []],
  'score': 74,
  'floor': []}]

In [267]:
# %%timeit 
from azul.ai import get_random_action, get_action_space, play, is_terminal, get_reward, MCTS_node, get_winner
from azul.logic import random_move 

t = azul.Table()
obs = t.get_observation()
obsOld = deepcopy(obs)

root = MCTS_node(obsOld)
MCTS_node.grow(root, timeout=1.0)

# action = get_random_action(obs)  # 35 us
action, _ = MCTS_node.get_best_action(root)

play(obs, action)

# random_move(obs)  # 19.9 us
# get_action_space(obs)
# play(obs, action)
# action, obs
# get_reward(obs)
# len(root.action)
# root.rollout()

# root.print()
rootNew = MCTS_node.search_node(root, obs)
# obs, obsOld
rootNew.print()
root.print()

self.numRolls=26, self.numWins=18, self.state['activePlayer']=1
	Action		UCB	WRatio	NumSims
	[-1, 3, -1]	2.55	0.000	1
	[-1, 3, 0]	3.55	1.000	1
	[-1, 3, 4]	3.55	1.000	1
	[-1, 4, 3]	2.55	0.000	1
	[0, 4, 1]	2.55	0.000	1
	[0, 4, 2]	2.55	0.000	1
	[0, 4, 4]	3.55	1.000	1
	[0, 5, 2]	2.55	0.000	1
	[0, 5, 4]	2.55	0.000	1
	[1, 1, 0]	2.55	0.000	1
	[1, 1, 3]	2.55	0.000	1
	[1, 2, -1]	2.55	0.000	1
	[1, 2, 0]	2.55	0.000	1
	[1, 2, 1]	2.55	0.000	1
	[1, 5, -1]	3.55	1.000	1
	[2, 3, 4]	3.55	1.000	1
	[2, 4, 1]	2.55	0.000	1
	[2, 4, 2]	2.55	0.000	1
	[2, 4, 4]	2.55	0.000	1
	[3, 2, 2]	3.55	1.000	1
	[3, 4, 3]	2.55	0.000	1
	[3, 4, 4]	2.55	0.000	1
	[3, 5, 0]	3.55	1.000	1
	[3, 5, 1]	2.55	0.000	1
	[3, 5, 2]	3.55	1.000	1
self.numRolls=1468, self.numWins=0, self.state['activePlayer']=0
	Action		UCB	WRatio	NumSims
	[0, 3, -1]	1.41	0.200	10
	[0, 3, 0]	1.44	0.680	25
	[0, 3, 1]	1.39	0.438	16
	[0, 3, 2]	1.40	0.526	19
	[0, 3, 3]	1.40	0.471	17
	[0, 3, 4]	1.40	0.640	25
	[0, 4, -1]	1.44	0.333	12
	[0, 4, 0]	1.40	0.550	20
	[0, 4

In [30]:
# == takes 80.2 ns
actions = {'a':[1, 1, 2], 'b':[2, 1, 1], 'c':[3, 2, 1]}
actions2 = {'a':[1, 1, 2], 'b':[2, 1, 1]}
actions2['c'] = [3, 2, 1]

# == takes 64 ns
# actions = [[1, 1, 2], [2, 1, 1], [3, 2, 1]]
# actions2 = [[1, 1, 2], [2, 1, 1]]
# actions2.append([3, 2, 1])
# b = [1, 2]

child = {str(a): None for a in actions}

actions == actions2
# actions, actions2
# b == None
str(actions)

"{'a': [1, 1, 2], 'b': [2, 1, 1], 'c': [3, 2, 1]}"

In [2]:
%load_ext autoreload
%autoreload 2

from azul.ai import MCTS_node, get_random_action
from azul.logic import random_move, Table

t = Table()
obs = t.get_observation()

root = MCTS_node(obs, 0)
root.grow()

root.print()

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload
self.numRolls=2638, self.numWins=0, self.state['activePlayer']=0
	Action		UCB	WRatio	NumSims
	[0, 1, -1]	1.24	0.462	26
	[0, 1, 0]	1.23	0.417	24
	[0, 1, 1]	1.22	0.500	30
	[0, 1, 2]	1.23	0.440	25
	[0, 1, 3]	1.23	0.440	25
	[0, 1, 4]	1.23	0.440	25
	[0, 2, -1]	1.25	0.500	28
	[0, 2, 0]	1.25	0.481	27
	[0, 2, 1]	1.24	0.350	20
	[0, 2, 2]	1.24	0.545	33
	[0, 2, 3]	1.24	0.462	26
	[0, 2, 4]	1.24	0.462	26
	[0, 3, -1]	1.24	0.559	34
	[0, 3, 0]	1.25	0.481	27
	[0, 3, 1]	1.24	0.571	35
	[0, 3, 2]	1.24	0.462	26
	[0, 3, 3]	1.23	0.440	25
	[0, 3, 4]	1.25	0.500	28
	[0, 5, -1]	1.25	0.595	37
	[0, 5, 0]	1.23	0.440	25
	[0, 5, 1]	1.23	0.440	25
	[0, 5, 2]	1.22	0.391	23
	[0, 5, 3]	1.22	0.391	23
	[0, 5, 4]	1.25	0.500	28
	[1, 3, -1]	1.24	0.583	36
	[1, 3, 0]	1.23	0.516	31
	[1, 3, 1]	1.25	0.481	27
	[1, 3, 2]	1.23	0.531	32
	[1, 3, 3]	1.23	0.440	25
	[1, 3, 4]	1.24	0.571	35
	[1, 4, -1]	1.25	0.381	21
	[1, 4, 0]	1.25	0.381	21
	[1, 4, 1]	1.

In [11]:
a = 1 
b = None

if a is not None:
    print('not none')

if a is None or b is None:
    print('none')

not none
none


In [37]:
grid = np.array([
    [0, 2, 3, 4, 5],
    [5, 1, 2, 3, 4],
    [4, 5, 1, 2, 3],
    [3, 4, 5, 1, 2],
    [2, 3, 4, 5, 1]])
np.sum(grid == 1)

discard = [1, 2, 2, 1, 2, 4]
# if discard.count(-1) > 0:
#     discard.remove(-1)
# np.random.permutation(discard)
# discard.remove(1)
discard.clear()
discard

[]

In [157]:
np.random.seed(100)
t = azul.Table()

# t.player[0].grid = np.array([
#     [1, 2, 3, 4, 5],
#     [0, 1, 0, 3, 4],
#     [4, 0, 1, 0, 3],
#     [0, 4, 0, 0, 2],
#     [0, 3, 4, 0, 0]])

# t.step_move(mark=5, factoryIdx=0, playerIdx=0, row=1)
# t.step_move(mark=5, factoryIdx=6, playerIdx=0, row=2)
# t.step_move(mark=1, factoryIdx=-1, playerIdx=0, row=4)
# t.print()
# t.player[0].print()
obs = t.get_observation()

# mark, factoryIdx, row = azul.random_move(0, obs)
# mark, factoryIdx, row
playerPolicyFcn = [azul.random_move] * 3
t.step_round(playerPolicyFcn)
# mark, factoryIdx, row = playerPolicyFcn[0](
#     0, obs)
# len(obs['factory'])
t.print()

[]
[]
[]
[]
[]
  []
[[], [3], [2], [], [4, 4, 4]]
[[1. 2. 3. 4. 5.]
 [5. 0. 2. 0. 4.]
 [4. 5. 0. 0. 0.]
 [3. 4. 0. 1. 0.]
 [2. 0. 0. 0. 0.]]
[]
8
---
[[], [3], [4], [2, 2], []]
[[1. 2. 3. 4. 5.]
 [5. 1. 2. 0. 4.]
 [0. 5. 1. 2. 3.]
 [3. 0. 0. 0. 0.]
 [0. 3. 0. 5. 0.]]
[]
31
---




In [147]:
t.print()
t.player[0].print()
t.player[1].print()

obs = t.get_observation()
azul.valid_move(obs,playerIdx=0, factoryIdx=-1, mark=5, row=1)

[]
[]
[]
[]
[]
  [1, 1, 1]
---
[[3], [3], [5], [4, 4, 4], [5, 5]]
[[0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 0. 2. 0.]
 [0. 0. 0. 0. 0.]
 [0. 3. 0. 0. 0.]]
[-1, 3, 3, 3]
4
---
[[5], [5], [2, 2, 2], [5, 5, 5], [4, 4, 4, 4, 4]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[5, 5]
0
---


False